version: '3.3'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ponimon4ik/foodgram-project-react:latest
    container_name: web
    restart: always
    volumes:
      - static_value:/app/django_static/
      - media_value:/app/django_media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_value:/app/django_staic
      - media_value:/app/django_media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
      - frontend
volumes:
  static_value:
  media_value:
