# Generated by Django 2.2.16 on 2022-01-19 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20220119_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritesRecipe',
            new_name='FavoriteRecipe',
        ),
    ]
