# Generated by Django 2.2.16 on 2022-01-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220120_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
