# Generated by Django 2.2.16 on 2022-01-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20220126_1937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_ingredient_in_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='tagrecipe',
            name='unique_tag_in_recipe',
        ),
    ]
